#pragma once
/********************************************************************
//    Created:     2025/05/29  14:02:44
//    File Name:   D:\XEngine_OPenSource\XEngine_Module\XEngine_AIApi\AIApi_Define.h
//    File Path:   D:\XEngine_OPenSource\XEngine_Module\XEngine_AIApi
//    File Base:   AIApi_Define
//    File Ext:    h
//    Project:     XEngine
//    Author:      qyt
//    Purpose:     AI接口导出函数
//    History:
*********************************************************************/
//////////////////////////////////////////////////////////////////////////
//                        导出的回调函数
//////////////////////////////////////////////////////////////////////////
typedef void(XCALLBACK* CALLBACK_XENGINE_MODULE_AIAPI_CHAT)(XNETHANDLE xhToken, LPCXSTR lpszModelName, LPCXSTR lpszMsgBuffer, int nMsgLen, bool bThink, XPVOID lParam);
//////////////////////////////////////////////////////////////////////////
//                        导出函数
//////////////////////////////////////////////////////////////////////////
extern "C" XLONG AIApi_GetLastError(int *pInt_ErrorCode = NULL);
/************************************************************************/
/*                        AI对话模型导出函数                            */
/************************************************************************/
/********************************************************************
函数名称：AIApi_Chat_Create
函数功能：AI对话模型初始化
 参数.一：pxhToken
  In/Out：Out
  类型：句柄
  可空：N
  意思：输出初始化成功的句柄
 参数.二：lpszAPIUrl
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入模型API地址
 参数.三：lpszAPIKey
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入模型的KEY
 参数.四：fpCall_Chat
  In/Out：In/Out
  类型：回调函数
  可空：N
  意思：对话输出信息
 参数.五：lParam
  In/Out：In/Out
  类型：无类型指针
  可空：Y
  意思：回调函数自定义参数
 参数.六：bHistory
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：是否启用历史会话功能
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AIApi_Chat_Create(XNETHANDLE* pxhToken, LPCXSTR lpszAPIUrl, LPCXSTR lpszAPIKey, CALLBACK_XENGINE_MODULE_AIAPI_CHAT fpCall_Chat, XPVOID lParam = NULL, bool bHistory = true);
/********************************************************************
函数名称：AIApi_Chat_Excute
函数功能：执行对话
 参数.一：xhToken
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的句柄
 参数.二：lpszModelName
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入模型名称
 参数.三：lpszMSGBuffer
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要对话的数据
 参数.四：nMSGLen
  In/Out：In
  类型：整数型
  可空：N
  意思：输入对话数据大小
 参数.五：bStream
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：是否使用流式数据回复
 参数.六：nMaxToken
  In/Out：In
  类型：整数型
  可空：Y
  意思：允许的最大token个数
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AIApi_Chat_Excute(XNETHANDLE xhToken, LPCXSTR lpszModelName, LPCXSTR lpszMSGBuffer, int nMSGLen, bool bStream = false, int nMaxToken = 0);
/********************************************************************
函数名称：AIApi_Chat_SetRole
函数功能：设置系统角色
 参数.一：xhToken
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的句柄
 参数.二：lpszModelName
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入系统角色信息,比如:你是一个C/C++语言的开发大师
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AIApi_Chat_SetRole(XNETHANDLE xhToken, LPCXSTR lpszRoleName);
/********************************************************************
函数名称：AIApi_Chat_Clear
函数功能：清理对话历史记录
 参数.一：xhToken
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的句柄
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AIApi_Chat_Clear(XNETHANDLE xhToken);
/********************************************************************
函数名称：AIApi_Chat_GetStatus
函数功能：获取执行状态
 参数.一：xhToken
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的句柄
 参数.二：pbComplete
  In/Out：Out
  类型：逻辑型指针
  可空：N
  意思：输出是否执行完毕
 参数.三：pInt_HTTPCode
  In/Out：Out
  类型：整数型指针
  可空：Y
  意思：输出HTTP状态码
 参数.四：bWaitExist
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：是否等待执行完毕
返回值
  类型：逻辑型
  意思：是否成功
备注：pbComplete没有执行完毕需要等待执行完毕
*********************************************************************/
extern "C" bool AIApi_Chat_GetStatus(XNETHANDLE xhToken, bool* pbComplete, int* pInt_HTTPCode = NULL, bool bWaitExist = true);
/********************************************************************
函数名称：AIApi_Chat_Destory
函数功能：销毁一个对话模型
 参数.一：xhToken
  In/Out：In
  类型：句柄
  可空：N
  意思：要操作的模型句柄
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AIApi_Chat_Destory(XNETHANDLE xhToken);
/************************************************************************/
/*                        AI图像处理模型导出函数                        */
/************************************************************************/
/********************************************************************
函数名称：AIApi_Vision_Create
函数功能：AI图像处理模型初始化
 参数.一：pxhToken
  In/Out：Out
  类型：句柄
  可空：N
  意思：输出初始化成功的句柄
 参数.二：lpszAPIUrl
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入模型API地址
 参数.三：lpszAPIKey
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入模型的KEY
 参数.四：fpCall_Chat
  In/Out：In/Out
  类型：回调函数
  可空：N
  意思：对话输出信息
 参数.五：lParam
  In/Out：In/Out
  类型：无类型指针
  可空：Y
  意思：回调函数自定义参数
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AIApi_Vision_Create(XNETHANDLE* pxhToken, LPCXSTR lpszAPIUrl, LPCXSTR lpszAPIKey, CALLBACK_XENGINE_MODULE_AIAPI_CHAT fpCall_Chat, XPVOID lParam = NULL);
/********************************************************************
函数名称：AIApi_Vision_ExcuteParse
函数功能：处理图像理解
 参数.一：xhToken
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的句柄
 参数.二：lpszModelName
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入模型名称
 参数.三：lpszUrlBase
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入URL或者BASE64编码数据
 参数.四：lpszMSGBuffer
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入怎么处理图像数据
 参数.五：nMSGLen
  In/Out：In
  类型：整数型
  可空：N
  意思：输入lpszMSGBuffer大小
 参数.六：bStream
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：是否使用流式数据回复
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AIApi_Vision_ExcuteParse(XNETHANDLE xhToken, LPCXSTR lpszModelName, LPCXSTR lpszUrlBase, LPCXSTR lpszMSGBuffer, int nMSGLen, bool bStream = false);
/********************************************************************
函数名称：AIApi_Vision_ExcuteCrete
函数功能：AI创建图像
 参数.一：xhToken
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的句柄
 参数.二：lpszModelName
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入模型名称
 参数.三：lpszMSGSize
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入创建的分辨率1024x1024.需要根据模型来设置
 参数.四：lpszMSGBuffer
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：描述要创建的什么样的图像
 参数.五：nMSGLen
  In/Out：In
  类型：整数型
  可空：N
  意思：输入lpszMSGBuffer大小
 参数.六：pptszMSGBuffer
  In/Out：Out
  类型：二级指针
  可空：Y
  意思：输出创建后的图像数据,此内存需要用户释放,如果bCallback为真,那么此参数不起作用
 参数.七：pInt_MSGLen
  In/Out：Out
  类型：整数型指针
  可空：Y
  意思：输出图像数据大小,如果bCallback为真,那么此参数不起作用
 参数.八：bCallback
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：输入图像输出方法,可以为回调或者直接输出
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AIApi_Vision_ExcuteCrete(XNETHANDLE xhToken, LPCXSTR lpszModelName, LPCXSTR lpszMSGSize, LPCXSTR lpszMSGBuffer, int nMSGLen, XCHAR** pptszMSGBuffer, int* pInt_MSGLen, bool bCallback = false);
/********************************************************************
函数名称：AIApi_Vision_GetStatus
函数功能：获取执行状态
 参数.一：xhToken
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的句柄
 参数.二：pbComplete
  In/Out：Out
  类型：逻辑型指针
  可空：N
  意思：输出是否执行完毕
 参数.三：pInt_HTTPCode
  In/Out：Out
  类型：整数型指针
  可空：Y
  意思：输出HTTP状态码
 参数.四：bWaitExist
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：是否等待执行完毕
返回值
  类型：逻辑型
  意思：是否成功
备注：pbComplete没有执行完毕需要等待执行完毕
*********************************************************************/
extern "C" bool AIApi_Vision_GetStatus(XNETHANDLE xhToken, bool* pbComplete, int* pInt_HTTPCode = NULL, bool bWaitExist = true);
/********************************************************************
函数名称：AIApi_Vision_Destory
函数功能：销毁一个对话模型
 参数.一：xhToken
  In/Out：In
  类型：句柄
  可空：N
  意思：要操作的模型句柄
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AIApi_Vision_Destory(XNETHANDLE xhToken);
/************************************************************************/
/*                        AI帮助 导出函数                               */
/************************************************************************/
/********************************************************************
函数名称：AIApi_Help_Base64EncodecFile
函数功能：转换文件到BASE64请求格式
 参数.一：lpszFileName
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要读取的文件
 参数.二：pptszMSGBuffer
  In/Out：Out
  类型：二级指针
  可空：N
  意思：输出转换后的缓冲区,此内存需要用户手动释放
 参数.三：pInt_MSGLen
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出缓冲区大小
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AIApi_Help_Base64EncodecFile(LPCXSTR lpszFileName, XCHAR** pptszMSGBuffer, int* pInt_MSGLen);
/********************************************************************
函数名称：AIApi_Help_Base64EncodecMemory
函数功能：转换内存数据到BASE64请求格式
 参数.一：lpszFileExt
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：文件的后缀名格式
 参数.二：lpszMSGBuffer
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入内存缓冲区
 参数.三：nMSGLen
  In/Out：In
  类型：整数型
  可空：N
  意思：输入缓冲区大小
 参数.四：pptszMSGBuffer
  In/Out：Out
  类型：二级指针
  可空：N
  意思：输出转换后的缓冲区,此内存需要用户手动释放
 参数.五：pInt_MSGLen
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出缓冲区大小
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AIApi_Help_Base64EncodecMemory(LPCXSTR lpszFileExt, LPCXSTR lpszMSGBuffer, int nMSGLen, XCHAR** pptszMSGBuffer, int* pInt_MSGLen);
/********************************************************************
函数名称：AIApi_Help_Base64DecodecFile
函数功能：BASE64格式内存缓冲区数据转文件
 参数.一：lpszMSGBuffer
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入内存缓冲区
 参数.二：nMSGLen
  In/Out：In
  类型：整数型
  可空：N
  意思：输入缓冲区大小
 参数.三：lpszFileName
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要保存的文件地址
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AIApi_Help_Base64DecodecFile(LPCXSTR lpszMSGBuffer, int nMSGLen, LPCXSTR lpszFileName);
/********************************************************************
函数名称：AIApi_Help_Base64DecodecMemory
函数功能：BASE64格式内存缓冲区转为内存数据
 参数.一：lpszMSGBuffer
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入内存缓冲区
 参数.二：nMSGLen
  In/Out：In
  类型：整数型
  可空：N
  意思：输入缓冲区大小
 参数.三：ptszMSGBuffer
  In/Out：Out
  类型：字符指针
  可空：N
  意思：输出转换后的缓冲区
 参数.四：pInt_MSGLen
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出缓冲区大小
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AIApi_Help_Base64DecodecMemory(LPCXSTR lpszMSGBuffer, int nMSGLen, XCHAR* ptszMSGBuffer, int* pInt_MSGLen);