name: android build workflows

on:
  push:
    branches: 
      - develop

permissions:
  contents: read
  
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
    runs-on: ${{ matrix.os }}

    steps:
       # 检出您的主仓库代码
      - name: Checkout main repository code
        uses: actions/checkout@v4

      - name: Set TERM variable
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: install ndk
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
          unzip ./android-ndk-r27c-linux.zip
          mv ./android-ndk-r27c $HOME/android-ndk

      - name: Set up Dependency xengine Environment
        run: |
            latest_tag=$(curl -s https://api.github.com/repos/libxengine/libxengine/releases/latest | jq -r .tag_name)
            wget https://github.com/libxengine/libxengine/releases/download/$latest_tag/XEngine_Android_Arm64.zip
            unzip ./XEngine_Android_Arm64.zip -d ./XEngine_Android_Arm64
            mv XEngine_Android_Arm64 $HOME/XEngine_Android_Arm64
  
      - name: make
        run: | 
            cd XEngine_Module
            cd jsoncpp
            make PLATFORM=android
            cd ..
            cd tinyxml2
            make PLATFORM=android
            cd ..
            cd XEngine_InfoReport
            make PLATFORM=android
            cd ..
            cd XEngine_Token
            make PLATFORM=android
            cd ..
            cd XEngine_MSGNotify
            make PLATFORM=android
            cd ..
            cd XEngine_AIApi
            make PLATFORM=android