name: macos build workflows

on:
  push:
    branches:
      - 'master'
  
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-13
          - os: macos-14
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4
        
       # 检出依赖的xengine仓库到指定的xengine目录
      - name: Checkout dependency repository (xengine)
        uses: actions/checkout@v4
        with:
          repository: libxengine/libxengine
          path: libxengine

      - name: Set TERM variable
        run: echo "TERM=xterm" >> $GITHUB_ENV
        
      - name: brew install
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install sdl2  
          
      - name: Set up Dependency x86_64 Environment 
        if: matrix.os == 'macos-13'
        run: |
            cd libxengine
            chmod 777 *
            ./XEngine_LINEnv.sh -i 3
      - name: Set up Dependency Arm64 Environment 
        if: matrix.os == 'macos-14'
        run: |
            cd libxengine
            chmod 777 *
            ./XEngine_LINEnv.sh -i 0

            latest_tag=$(git ls-remote --tags --sort="v:refname" https://github.com/libxengine/libxengine.git | awk '{print $2}' | sed 's/refs\/tags\///' | tail -n 1)
            
            wget https://github.com/libxengine/libxengine/releases/download/$latest_tag/XEngine_Mac_Arm64.zip
            unzip ./XEngine_Mac_Arm64.zip -d ./XEngine_Mac_Arm64
            cd XEngine_Mac_Arm64

            sudo mkdir -p /usr/local/include
            sudo mkdir -p /usr/local/lib
            sudo cp -rf ./XEngine_Include /usr/local/include
            sudo find ./XEngine_Mac -name "*.dylib" -exec cp {} /usr/local/lib \;

      - name: make
        run: | 
            cd XEngine_Module
            cd jsoncpp
            make PLATFORM=mac
            cd ..
            cd tinyxml2
            make PLATFORM=mac
            cd ..
            cd XEngine_InfoReport
            make PLATFORM=mac
            cd ..
            cd XEngine_AVPlayer
            make PLATFORM=mac            