name: ubuntu build workflows

on:
  push:
    branches: 
      - 'master'
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: ubuntu-24.04
          - os: ubuntu-22.04-arm
          - os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}

    steps:
       # 检出您的主仓库代码
      - name: Checkout main repository code
        uses: actions/checkout@v4
        
       # 检出依赖的xengine仓库到指定的xengine目录
      - name: Checkout dependency repository (xengine)
        uses: actions/checkout@v4
        with:
          repository: libxengine/libxengine
          path: libxengine

      - name: install apt library
        if: matrix.os == 'ubuntu-22.04' || matrix.os == 'ubuntu-24.04'
        run: sudo apt install libsdl2-dev        

      - name: Set up Dependency ubuntu24.04 Environment
        if: matrix.os == 'ubuntu-24.04'
        run: |
            cd libxengine
            chmod 777 *
            sudo ./XEngine_LINEnv.sh -i 3
      - name: Set up Dependency ubuntu22.04 Environment
        if: matrix.os == 'ubuntu-22.04'
        run: |
            cd libxengine
            chmod 777 *
            sudo ./XEngine_LINEnv.sh -i 0

            latest_tag=$(curl -s https://api.github.com/repos/libxengine/libxengine/releases/latest | jq -r .tag_name)
            wget https://github.com/libxengine/libxengine/releases/download/$latest_tag/XEngine_UBuntu_22.04_x86-64.zip
            unzip ./XEngine_UBuntu_22.04_x86-64.zip -d ./XEngine_UBuntu_22.04_x86-64
            cd XEngine_UBuntu_22.04_x86-64
            
            sudo cp -rf ./XEngine_Include /usr/local/include
            sudo find ./XEngine_Linux -name "*.so" -exec cp {} /usr/local/lib \;         
            sudo ldconfig
      - name: Set up Dependency ubuntu22.04 arm64 Environment
        if: matrix.os == 'ubuntu-22.04-arm'
        run: |
            cd libxengine
            chmod 777 *
            sudo ./XEngine_LINEnv.sh -i 0

            latest_tag=$(curl -s https://api.github.com/repos/libxengine/libxengine/releases/latest | jq -r .tag_name)
            wget https://github.com/libxengine/libxengine/releases/download/$latest_tag/XEngine_UBuntu_22.04_Arm64.zip
            unzip ./XEngine_UBuntu_22.04_Arm64.zip -d ./XEngine_UBuntu_22.04_Arm64
            cd XEngine_UBuntu_22.04_Arm64
            
            sudo cp -rf ./XEngine_Include /usr/local/include
            sudo find ./XEngine_Linux -name "*.so" -exec cp {} /usr/local/lib \;         
            sudo ldconfig
      - name: Set up Dependency ubuntu24.04 arm64 Environment
        if: matrix.os == 'ubuntu-24.04-arm'
        run: |
            cd libxengine
            chmod 777 *
            sudo ./XEngine_LINEnv.sh -i 0

            latest_tag=$(curl -s https://api.github.com/repos/libxengine/libxengine/releases/latest | jq -r .tag_name)
            wget https://github.com/libxengine/libxengine/releases/download/$latest_tag/XEngine_UBuntu_24.04_Arm64.zip
            unzip ./XEngine_UBuntu_24.04_Arm64.zip -d ./XEngine_UBuntu_24.04_Arm64
            cd XEngine_UBuntu_24.04_Arm64
            
            sudo cp -rf ./XEngine_Include /usr/local/include
            sudo find ./XEngine_Linux -name "*.so" -exec cp {} /usr/local/lib \;         
            sudo ldconfig

      - name: make
        run: | 
            cd XEngine_Module
            cd jsoncpp
            make
            cd ..
            cd tinyxml2
            make
            cd ..
            cd XEngine_InfoReport
            make